version: '3'

# SHAREBOOK

services:
  api:
    image: sharebook
    ports:
      - "50709:80"
    build:
      context: ./ShareBook
      dockerfile: Dockerfile      
    depends_on:
        - db
    container_name: sharebook-api
  db:
    image: microsoft/mssql-server-linux:2017-latest
    restart: always
    environment:
      SA_PASSWORD: weWkh]6qA3jk
      ACCEPT_EULA: Y
    ports:
      - '1433:1433'
    expose:
      - '1433'
    container_name: sharebook-sql-server
    #    volumes: ( volume não funciona no Mac )
    #      - /home/sample:/var/opt/mssql
# networks: 
#  sharebook: 
#    driver: bridge
