version: '3.4'

services:
  sharebook.api:
    container_name: sharebook-api
    image: ${DOCKER_REGISTRY-}sharebookapi
    ports:
        - "50709:80"
    build:
      context: .
      dockerfile: ShareBook.Api/Dockerfile
    depends_on:
        - db
    networks:
        - sharebook

  db:
    image: microsoft/mssql-server-linux:2017-latest
    restart: always
    environment:
      SA_PASSWORD: weWkh]6qA3jk
      ACCEPT_EULA: Y
    ports:
      - '1433:1433'
    expose:
      - '1433'
    container_name: sharebook-sql-server
    #    volumes: ( volume não funciona no Mac )
    #      - /home/sample:/var/opt/mssql

# networks: 
#  sharebook: 
#    driver: bridge