name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
    - uses: actions/checkout@v2
      with:
        uses: actions/checkout@v2
        name: Build the Docker image
        context: ./ShareBook/ShareBook.Api
        tags: docker/image/name:latest
        file: ./Dockerfile      
      #run: docker build . --file ./ShareBook/ShareBook.Api/Dockerfile --tag sharebookapi:$(date +%s)
